/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/birth-chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calculate a birth chart
         * @description This endpoint calculates a birth chart for a given date, time, and location. It will give information such as: signs, houses, and aspects of the planets.
         */
        get: operations["calculateBirthChart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-transits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calculate daily transits
         * @description This endpoint calculates the transits for a given day at a given location. Useful for generating horoscopes.
         *
         *     If birth date is omitted you just get a chart for the current day along with ingresses and retrogrades, but no comparative aspects.
         */
        get: operations["calculateDailyTransits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generic-chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calculate a generic transit chart
         * @description This endpoint calculates the transits for a given date but does not require a location or birth data.
         *
         *     **Do not use this for personalised horoscopes**
         */
        get: operations["calculateGenericTransitChart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transits/range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calculate ranged transits
         * @description This endpoint calculates de-duplicated transit events across a UTC date range. It samples daily charts and returns one event per aspect with active dates, minimum orb, daily orb samples, summary metadata, ingresses, retrograde stations, and moon data.
         */
        get: operations["calculateTransitRange"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CalculateBirthChartResponse: {
            signs: {
                sun: components["schemas"]["ZodiacSignObject"];
                moon: components["schemas"]["ZodiacMoonSignObject"];
                ascendant: components["schemas"]["ZodiacSignObject"];
            };
            houses: components["schemas"]["HouseObject"][];
            planets: components["schemas"]["PlanetPositionObject"][];
            angles: components["schemas"]["PlanetPositionObject"][];
            aspects: components["schemas"]["AspectObject"][];
            declinations: components["schemas"]["AspectObject"][];
        };
        ZodiacSignObject: {
            value: components["schemas"]["ZodiacSign"];
            degree: number;
            cuspWarning: components["schemas"]["ZodiacSign"] & (string | null);
        };
        /** @enum {string} */
        ZodiacSign: "Aries" | "Taurus" | "Gemini" | "Cancer" | "Leo" | "Virgo" | "Libra" | "Scorpio" | "Sagittarius" | "Capricorn" | "Aquarius" | "Pisces";
        ZodiacMoonSignObject: components["schemas"]["ZodiacSignObject"] & {
            phase: components["schemas"]["MoonPhase"];
            isVoidOfCourse: boolean;
        };
        /** @enum {string} */
        MoonPhase: "New Moon" | "Waxing Crescent" | "First Quarter" | "Waxing Gibbous" | "Full Moon" | "Waning Gibbous" | "Last Quarter" | "Waning Crescent";
        HouseObject: {
            id: number;
            number: number;
            cusp: components["schemas"]["ZodiacPositionObject"];
        };
        ZodiacPositionObject: {
            longitude: number;
            degree: number;
            zodiac: components["schemas"]["ZodiacDetailsObject"];
        };
        ZodiacDetailsObject: {
            id: number;
            name: components["schemas"]["ZodiacSign"];
            lord: {
                id: components["schemas"]["PlanetId"];
                name: components["schemas"]["Planet"];
            };
        };
        /** @enum {integer} */
        PlanetId: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 15 | 100 | 103 | 104 | 105 | 107 | 108 | 109;
        /** @enum {string} */
        Planet: "Sun" | "Moon" | "Mercury" | "Venus" | "Mars" | "Jupiter" | "Saturn" | "Uranus" | "Neptune" | "Pluto" | "Chiron" | "Ascendant" | "True North Node" | "True South Node" | "Lilith" | "Nadir" | "Descendant" | "MidHeaven";
        PlanetPositionObject: components["schemas"]["GenericPlanetPositionObject"] & {
            houseNumber: number;
        };
        GenericPlanetPositionObject: {
            id: components["schemas"]["PlanetId"];
            name: components["schemas"]["Planet"];
            longitude: number;
            latitude?: number;
            isRetrograde: boolean;
            degree: number;
            zodiac: components["schemas"]["ZodiacDetailsObject"];
        };
        AspectObject: {
            planet1: {
                id: components["schemas"]["PlanetId"];
                name: components["schemas"]["Planet"];
                fromChart?: string;
            };
            planet2: {
                id: components["schemas"]["PlanetId"];
                name: components["schemas"]["Planet"];
                fromChart?: string;
            };
            aspect: {
                id: number;
                name: components["schemas"]["Aspect"];
            };
            orb: number;
            typeOfAspect: components["schemas"]["TypeOfAspect"];
        };
        /** @enum {string} */
        Aspect: "Conjunction" | "Opposition" | "Square" | "Semi Square" | "Sesquiquadrate" | "Trine" | "Sextile" | "Semi Sextile" | "Quincunx" | "Quintile" | "Bi Quintile" | "Parallel" | "Contraparallel";
        /** @enum {string} */
        TypeOfAspect: "transit-to-natal" | "natal-to-natal" | "transit-to-transit";
        /** @description An error response. Note that 'error' can be a string, or a ZodError object. */
        ErrorResponse: {
            error: string | {
                issues: {
                    code: string;
                    message: string;
                    path: string[];
                }[];
            };
        };
        CalculateDailyTransitsResponse: {
            transitChart: components["schemas"]["CalculateBirthChartResponse"];
            transitNatalAspects: components["schemas"]["AspectObject"][] | null;
            notableEvents: {
                retrogradePlanets: components["schemas"]["Planet"][];
                ingresses: components["schemas"]["IngressObject"][];
            };
        };
        IngressObject: {
            planet: components["schemas"]["Planet"];
            enteredSign: components["schemas"]["ZodiacSign"];
        };
        CalculateGenericTransitChartResponse: {
            chart: components["schemas"]["CalculateGenericChartResponse"];
            notableEvents: {
                retrogradePlanets: components["schemas"]["Planet"][];
                ingresses: components["schemas"]["IngressObject"][];
            };
        };
        CalculateGenericChartResponse: {
            signs: {
                sun: components["schemas"]["ZodiacSignObject"];
                moon: components["schemas"]["ZodiacMoonSignObject"];
            };
            planets: components["schemas"]["GenericPlanetPositionObject"][];
            aspects: components["schemas"]["AspectObject"][];
            declinations: components["schemas"]["AspectObject"][];
        };
        CalculateTransitRangeResponse: {
            range: {
                startDate: string;
                endDate: string;
                timezone: string;
            };
            summaryData: {
                dominantPlanets: components["schemas"]["DominantPlanetObject"][];
                dominantHouses: components["schemas"]["DominantHouseObject"][];
                dominantSigns: components["schemas"]["DominantSignObject"][];
                dominantAspectTypes: components["schemas"]["DominantAspectTypeObject"][];
                overallToneScore: number | null;
                sampleCount: number;
            };
            transitNatalEvents: components["schemas"]["TransitNatalRangeEventObject"][];
            transitTransitEvents: components["schemas"]["TransitTransitRangeEventObject"][];
            ingresses: components["schemas"]["RangeIngressObject"][];
            retrogrades: components["schemas"]["RangeRetrogradeObject"][];
            moonEvents: components["schemas"]["MoonEventObject"][];
        };
        DominantPlanetObject: {
            planet: components["schemas"]["Planet"];
            count: number;
            score: number;
        };
        DominantHouseObject: {
            houseNumber: number;
            count: number;
            score: number;
        };
        DominantSignObject: {
            sign: components["schemas"]["ZodiacSign"];
            count: number;
            score: number;
        };
        DominantAspectTypeObject: {
            aspect: components["schemas"]["Aspect"];
            count: number;
            score: number;
        };
        TransitNatalRangeEventObject: {
            aspect: {
                id: number;
                name: components["schemas"]["Aspect"];
            };
            firstSeen: string;
            activeFrom: string;
            exactPeakTime: string | null;
            activeUntil: string;
            minimumOrb: number;
            minimumOrbDate: string;
            orbAtStart: number | null;
            orbAtEnd: number | null;
            applyingAtStart: boolean | null;
            separatingAtEnd: boolean | null;
            exactInRange: boolean;
            importance: number;
            rank: number;
            samples: components["schemas"]["RangeAspectSampleObject"][];
            transitPlanet: components["schemas"]["Planet"];
            natalBody: components["schemas"]["Planet"];
            natalHouse: number | null;
            natalSign: components["schemas"]["ZodiacSign"];
            transitHouse: number | null;
            transitSign: components["schemas"]["ZodiacSign"];
        };
        RangeAspectSampleObject: {
            date: string;
            orb: number;
            applying: boolean | null;
            transitSign: components["schemas"]["ZodiacSign"];
            transitHouse: number | null;
            natalSign: components["schemas"]["ZodiacSign"] & (string | null);
            natalHouse: number | null;
        };
        TransitTransitRangeEventObject: {
            aspect: {
                id: number;
                name: components["schemas"]["Aspect"];
            };
            firstSeen: string;
            activeFrom: string;
            exactPeakTime: string | null;
            activeUntil: string;
            minimumOrb: number;
            minimumOrbDate: string;
            orbAtStart: number | null;
            orbAtEnd: number | null;
            applyingAtStart: boolean | null;
            separatingAtEnd: boolean | null;
            exactInRange: boolean;
            importance: number;
            rank: number;
            samples: components["schemas"]["RangeAspectSampleObject"][];
            planet1: components["schemas"]["Planet"];
            planet2: components["schemas"]["Planet"];
            planet1House: number | null;
            planet1Sign: components["schemas"]["ZodiacSign"];
            planet2House: number | null;
            planet2Sign: components["schemas"]["ZodiacSign"];
        };
        RangeIngressObject: {
            planet: components["schemas"]["Planet"];
            fromSign: components["schemas"]["ZodiacSign"] & (string | null);
            toSign: components["schemas"]["ZodiacSign"];
            exactTimestamp: string | null;
            firstSeenDate: string;
            houseAfterIngress: number | null;
        };
        RangeRetrogradeObject: {
            planet: components["schemas"]["Planet"];
            /** @enum {string} */
            stationType: "retrograde" | "direct";
            exactTimestamp: string | null;
            firstSeenDate: string;
            sign: components["schemas"]["ZodiacSign"];
            degree: number;
        };
        MoonEventObject: {
            date: string;
            moonSign: components["schemas"]["ZodiacMoonSignObject"];
            voidOfCourseWindows: {
                startsAt: string;
                endsAt: string;
            }[];
            majorMoonAspects: components["schemas"]["AspectObject"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaCalculateBirthChartResponse = components['schemas']['CalculateBirthChartResponse'];
export type SchemaZodiacSignObject = components['schemas']['ZodiacSignObject'];
export type SchemaZodiacSign = components['schemas']['ZodiacSign'];
export type SchemaZodiacMoonSignObject = components['schemas']['ZodiacMoonSignObject'];
export type SchemaMoonPhase = components['schemas']['MoonPhase'];
export type SchemaHouseObject = components['schemas']['HouseObject'];
export type SchemaZodiacPositionObject = components['schemas']['ZodiacPositionObject'];
export type SchemaZodiacDetailsObject = components['schemas']['ZodiacDetailsObject'];
export type SchemaPlanetId = components['schemas']['PlanetId'];
export type SchemaPlanet = components['schemas']['Planet'];
export type SchemaPlanetPositionObject = components['schemas']['PlanetPositionObject'];
export type SchemaGenericPlanetPositionObject = components['schemas']['GenericPlanetPositionObject'];
export type SchemaAspectObject = components['schemas']['AspectObject'];
export type SchemaAspect = components['schemas']['Aspect'];
export type SchemaTypeOfAspect = components['schemas']['TypeOfAspect'];
export type SchemaErrorResponse = components['schemas']['ErrorResponse'];
export type SchemaCalculateDailyTransitsResponse = components['schemas']['CalculateDailyTransitsResponse'];
export type SchemaIngressObject = components['schemas']['IngressObject'];
export type SchemaCalculateGenericTransitChartResponse = components['schemas']['CalculateGenericTransitChartResponse'];
export type SchemaCalculateGenericChartResponse = components['schemas']['CalculateGenericChartResponse'];
export type SchemaCalculateTransitRangeResponse = components['schemas']['CalculateTransitRangeResponse'];
export type SchemaDominantPlanetObject = components['schemas']['DominantPlanetObject'];
export type SchemaDominantHouseObject = components['schemas']['DominantHouseObject'];
export type SchemaDominantSignObject = components['schemas']['DominantSignObject'];
export type SchemaDominantAspectTypeObject = components['schemas']['DominantAspectTypeObject'];
export type SchemaTransitNatalRangeEventObject = components['schemas']['TransitNatalRangeEventObject'];
export type SchemaRangeAspectSampleObject = components['schemas']['RangeAspectSampleObject'];
export type SchemaTransitTransitRangeEventObject = components['schemas']['TransitTransitRangeEventObject'];
export type SchemaRangeIngressObject = components['schemas']['RangeIngressObject'];
export type SchemaRangeRetrogradeObject = components['schemas']['RangeRetrogradeObject'];
export type SchemaMoonEventObject = components['schemas']['MoonEventObject'];
export type $defs = Record<string, never>;
export interface operations {
    calculateBirthChart: {
        parameters: {
            query: {
                /** @description The UTC year of birth */
                year: number;
                /** @description The UTC month of birth. NOT zero-indexed */
                month: number;
                /** @description The UTC day of birth */
                day: number;
                /** @description The UTC hour of birth */
                hour?: number | null;
                /** @description The UTC minute of birth */
                minute?: number | null;
                /** @description The latitude of the birth location */
                latitude?: number | null;
                /** @description The longitude of the birth location */
                longitude?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculateBirthChartResponse"];
                };
            };
            /** @description User Error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Calculation Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    calculateDailyTransits: {
        parameters: {
            query?: {
                /** @description The UTC year of birth */
                birthYear?: number;
                /** @description The UTC month of birth. NOT zero-indexed */
                birthMonth?: number;
                /** @description The UTC day of birth */
                birthDay?: number;
                /** @description The UTC minute of birth */
                birthMinute?: number | null;
                /** @description The UTC hour of birth */
                birthHour?: number | null;
                /** @description The latitude of the birth location */
                birthLatitude?: number | null;
                /** @description The longitude of the birth location */
                birthLongitude?: number | null;
                /** @description The UTC year to calculate transits for */
                transitYear?: number;
                /** @description The UTC month to calculate transits for. NOT zero-indexed */
                transitMonth?: number;
                /** @description The UTC day to calculate transits for */
                transitDay?: number;
                /** @description The latitude of the location to calculate transits for */
                transitLatitude?: number | null;
                /** @description The longitude of the location to calculate transits for */
                transitLongitude?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculateDailyTransitsResponse"];
                };
            };
            /** @description User Error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Calculation Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    calculateGenericTransitChart: {
        parameters: {
            query: {
                /** @description The UTC year to calculate transits for */
                year: number;
                /** @description The UTC month to calculate transits for. NOT zero-indexed */
                month: number;
                /** @description The UTC day to calculate transits for */
                day: number;
                /** @description The UTC hour to calculate transits for */
                hour?: number | null;
                /** @description The UTC minute to calculate transits for */
                minute?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculateGenericTransitChartResponse"];
                };
            };
            /** @description User Error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Calculation Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    calculateTransitRange: {
        parameters: {
            query: {
                /** @description The UTC year of birth */
                birthYear: number;
                /** @description The UTC month of birth. NOT zero-indexed */
                birthMonth: number;
                /** @description The UTC day of birth */
                birthDay: number;
                /** @description The UTC hour of birth */
                birthHour?: number | null;
                /** @description The UTC minute of birth */
                birthMinute?: number | null;
                /** @description The latitude of the birth location */
                birthLatitude?: number | null;
                /** @description The longitude of the birth location */
                birthLongitude?: number | null;
                /** @description The UTC start year for the transit range */
                transitStartYear: number;
                /** @description The UTC start month for the transit range. NOT zero-indexed */
                transitStartMonth: number;
                /** @description The UTC start day for the transit range */
                transitStartDay: number;
                /** @description The UTC end year for the transit range */
                transitEndYear: number;
                /** @description The UTC end month for the transit range. NOT zero-indexed */
                transitEndMonth: number;
                /** @description The UTC end day for the transit range */
                transitEndDay: number;
                /** @description The latitude of the location to calculate transits for */
                transitLatitude?: number | null;
                /** @description The longitude of the location to calculate transits for */
                transitLongitude?: number | null;
                /** @description Timezone label for the requested range. Event timestamps are currently UTC. */
                timezone?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculateTransitRangeResponse"];
                };
            };
            /** @description User Error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Calculation Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
